# Generated by Django 5.1.7 on 2025-04-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
